services:
  app:
    image: node:latest
    container_name: app-test
    ports:
      - 80:80
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
  db:
    image: postgres:latest
    container_name: postgres-sql-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sales_db
